### ISSUE TITLE
Rebase application from the original boilerplate

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/electron-wrapper#5]
Our kiosk wrapper application is based on Electron and was forked from the [szwacz/electron-boilerplate](https://github.com/szwacz/electron-boilerplate) project. This boilerplate provides a good structure for handling the development and production building of electron apps.

We forked off a long while back and haven't kept up with changes in the boilerplate or the newer versions of Electron. This was fine for a while, but we've recently run into some issues builing out wrapper application on the Windows environment. Since we're building out a few new exhibits in Windows, it seems like a good time to rebase (pull down updates from the `szwacz/electron-boilerplate` project and re-insert our customizations.

I added the `szwacz/electron-boilerplate` as an upstream remote and am in the process of adding our customizations back into the boilerplate and removing the specifics that don't relate to this project.

@tnordberg, @azuldev1, @heidgera  I'm tagging you on this, so that you know about the changes.

@bherr2 you also might be interested since we'll be using some incarnation of this tool for our deployment of the [xMacroscope](https://github.com/cns-iu/xmacroscope) application in our kiosks.

I post again once we have a version that replicates existing functionality and also builds properly on MacOS, Linux, and Windows.

**Comment by tnordberg** [comment]
The `multiple-displays` branch is up to date with the additions I made for the Theatrical Gaming project. @heidgera,  which branch includes your Big Astronaut additions? Do you think that code is in a state where we could use it as the reference for this rebase?

**Comment by bryankennedy** [comment]
@heidgera is your display handling work embedded in the https://github.com/scimusmn/jts-astronaut project? Maybe we could break the window handling into a module that could be installed in both environments. This app's goal is to be a content-less wrapper, but there are times when we want the app logic to live within the Electron system. It would be nice to not maintain the windowing controls across those multiple projects.

**Comment by bryankennedy** [comment]
I completed the rebase and will be moving the work over to Stele (#8)

I talked with @heidgera in person and he demonstrated the windowing work that he's done in the [jts-astronaut](https://github.com/scimusmn/jts-astronaut/tree/PureElectron) repo. I'll merge that with @tnordberg's work and commit that to Stele.
